export const MOCK_GAMES = [
  {
    id: 'this is a game Id',
    title: 'this is a game',
    players: [
      {
        userAlias: 'someAlias',
        userAvatar: 'anotherAvater',
        userId: 'randomUser',
        online: false,
        teamId: 'someId',
        teamAlias: 'alligatorTeam',
        teamAvatar: 'someAvatar',
        teamColor: '#aae3d5',
      },
      {
        userAlias: 'someAlias',
        userAvatar: 'anotherAvater',
        userId: 'anotherRandomUser',
        online: false,
        teamId: 'someId',
        teamAlias: 'alligatorTeam',
        teamAvatar: 'someAvatar',
        teamColor: '#aae3d5',
      },
      {
        userAlias: 'someAlias',
        userAvatar: 'anotherAvater',
        userId: 'yetAnotherRandomUser',
        online: false,
        teamId: 'someId',
        teamAlias: 'alligatorTeam',
        teamAvatar: 'someAvatar',
        teamColor: '#aae3d5',
      },
    ],
    scores: [],
    groupScores: {
      average: {
        correct: 0,
        incorrect: 0,
        unanswered: 0,
        answered: 0,
      },
      points: {
        average: 0,
        highest: 0,
      },
      participants: 2,
      leaderboard: [
        {
          userId: 'randomUser',
          userAlias: 'someAlias',
          points: 0,
        },
        {
          userId: 'randomUser',
          userAlias: 'someAlias',
          points: 0,
        },
        {
          userId: 'randomUser',
          userAlias: 'someAlias',
          points: 0,
        },
      ],
    },
    status: {
      scheduled: true,
      started: false,
      closed: false,
      organizer: 'yetAnotherRandomUser',
      timed: true,
      maxTime: 400,
      start: new Date(),
    },
    info: {
      activityId: 'randomActivityId',
      activityTitle: 'someTitle',
      language: 'ca',
      keywords: ['cats', 'cakes'],
      type: 'best-option',
    },
  },
  {
    id: 'this is another game Id',
    title: 'this is not a game',
    players: [
      {
        userAlias: 'someAlias',
        userAvatar: 'anotherAvater',
        userId: 'randomUser',
        online: false,
        teamId: 'someId',
        teamAlias: 'alligatorTeam',
        teamAvatar: 'someAvatar',
        teamColor: '#aae3d5',
      },
      {
        userAlias: 'someAlias',
        userAvatar: 'anotherAvater',
        userId: 'anotherRandomUser',
        online: false,
        teamId: 'someId',
        teamAlias: 'alligatorTeam',
        teamAvatar: 'someAvatar',
        teamColor: '#aae3d5',
      },
      {
        userAlias: 'someAlias',
        userAvatar: 'anotherAvater',
        userId: 'yetAnotherRandomUser',
        online: false,
        teamId: 'someId',
        teamAlias: 'alligatorTeam',
        teamAvatar: 'someAvatar',
        teamColor: '#aae3d5',
      },
      {
        userAlias: 'someAlias',
        userAvatar: 'anotherAvater',
        userId: 'someUser',
        online: false,
        teamId: 'someId',
        teamAlias: 'alligatorTeam',
        teamAvatar: 'someAvatar',
        teamColor: '#aae3d5',
      },
    ],
    scores: [
      {
        id: 'randomScoreId',
        userId: 'anotherRandomUser',
        activityId: 'blue',
        correct: 2,
        incorrect: 2,
        total: 6,
        time: 245,
        maxTime: 200,
        pointsPerQuestion: 5,
        answers: [],
      },
      {
        id: 'randomScoreId2',
        userId: 'randomUser',
        activityId: 'green',
        correct: 4,
        incorrect: 1,
        total: 6,
        time: 285,
        maxTime: 200,
        pointsPerQuestion: 5,
        answers: [],
      },
      {
        id: 'randomScoreId3',
        userId: 'yetAnotherRandomUser',
        activityId: 'purple',
        correct: 4,
        incorrect: 2,
        total: 6,
        time: 293,
        maxTime: 200,
        pointsPerQuestion: 5,
        answers: [],
      },
      {
        id: 'randomScoreId4',
        userId: 'someUser',
        activityId: 'yellow',
        correct: 5,
        incorrect: 0,
        total: 6,
        time: 302,
        maxTime: 200,
        pointsPerQuestion: 5,
        answers: [],
      },
    ],
    groupScores: {
      average: {
        correct: 0,
        incorrect: 0,
        unanswered: 0,
        answered: 0,
      },
      points: {
        average: 0,
        highest: 0,
      },
      participants: 2,
      leaderboard: [
        {
          userId: 'randomUser',
          userAlias: 'someAlias',
          points: 0,
        },
        {
          userId: 'randomUser',
          userAlias: 'someAlias',
          points: 0,
        },
        {
          userId: 'randomUser',
          userAlias: 'someAlias',
          points: 0,
        },
      ],
    },
    status: {
      scheduled: true,
      started: true,
      closed: true,
      organizer: 'someUser',
      timed: true,
      maxTime: 300,
      start: new Date(),
    },
    info: {
      activityId: 'randomActivityId2',
      activityTitle: 'someTitleOfTheActivity',
      language: 'en',
      keywords: ['idioms', 'cakes'],
      type: 'select-text',
    },
  },
];
