export const MOCK_GAMES = [
  {
    id: 'this is a game Id',
    title: 'this is a game',
    users: [
      { id: 'randomUser', team: 'red', role: 'player' },
      { id: 'anotherRandomUser', team: 'blue', role: 'player' },
      { id: 'yetAnotherRandomUser', team: 'red', role: 'organizer' },
    ],
    scores: [],
    status: {
      scheduled: true,
      started: false,
      closed: false,
      organizer: 'yetAnotherRandomUser',
      timed: true,
      maxTime: 400,
      start: new Date(),
    },
    info: {
      activityId: 'randomActivityId',
      activityTitle: 'someTitle',
      language: 'ca',
      keywords: ['cats', 'cakes'],
      type: 'best-option',
    },
  },
  {
    id: 'this is another game Id',
    title: 'this is not a game',
    users: [
      { id: 'randomUser', team: 'green', role: 'player' },
      { id: 'anotherRandomUser', team: 'blue', role: 'player' },
      { id: 'yetAnotherRandomUser', team: 'purple', role: 'player' },
      { id: 'someUser', team: 'yellow', role: 'organizer' },
    ],
    scores: [
      {
        id: 'randomScoreId',
        userId: 'anotherRandomUser',
        teamId: 'blue',
        right: 2,
        wrong: 2,
        unanswered: 2,
        total: 6,
        timeToComplete: 245,
        inTime: true,
        completed: false,
      },
      {
        id: 'randomScoreId2',
        userId: 'randomUser',
        teamId: 'green',
        right: 4,
        wrong: 1,
        unanswered: 1,
        total: 6,
        timeToComplete: 285,
        inTime: true,
        completed: false,
      },
      {
        id: 'randomScoreId3',
        userId: 'yetAnotherRandomUser',
        teamId: 'purple',
        right: 4,
        wrong: 2,
        unanswered: 0,
        total: 6,
        timeToComplete: 293,
        inTime: true,
        completed: true,
      },
      {
        id: 'randomScoreId4',
        userId: 'someUser',
        teamId: 'yellow',
        right: 5,
        wrong: 0,
        unanswered: 1,
        total: 6,
        timeToComplete: 302,
        inTime: false,
        completed: false,
      },
    ],
    status: {
      scheduled: true,
      started: true,
      closed: true,
      organizer: 'someUser',
      timed: true,
      maxTime: 300,
      start: new Date(),
    },
    info: {
      activityId: 'randomActivityId2',
      activityTitle: 'someTitleOfTheActivity',
      language: 'en',
      keywords: ['idioms', 'cakes'],
      type: 'select-text',
    },
  },
];
